Repository ryurbsgks5114/LegendOfDelivery, pull requests merged in 2024-06, with the labels that each got.

#59 feat: 🎉 add 가게별 리뷰 목록 조회
  src/main/java/com/sparta/legendofdelivery/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/legendofdelivery/domain/review/dto/StoreByReviewResponseDto.java
  src/main/java/com/sparta/legendofdelivery/domain/review/dto/StoreReviewResponseDto.java
  src/main/java/com/sparta/legendofdelivery/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/legendofdelivery/domain/review/service/ReviewService.java
Labels: feat

#67 feat: 좋아요 기능 구현
  src/main/java/com/sparta/legendofdelivery/domain/like/controller/LikeController.java
  src/main/java/com/sparta/legendofdelivery/domain/like/entity/Like.java
  src/main/java/com/sparta/legendofdelivery/domain/like/repository/LikeRepository.java
  src/main/java/com/sparta/legendofdelivery/domain/like/service/LikeService.java
  src/main/java/com/sparta/legendofdelivery/domain/user/security/UserDetailsImpl.java
Labels: feat

#69 feat : 🎉 add 리뷰 삭제 기능 추가
  src/main/java/com/sparta/legendofdelivery/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/legendofdelivery/domain/review/dto/DeleteReviewRequestDto.java
  src/main/java/com/sparta/legendofdelivery/domain/review/entity/ErrorCode.java
  src/main/java/com/sparta/legendofdelivery/domain/review/entity/successMessage.java
  src/main/java/com/sparta/legendofdelivery/domain/review/service/ReviewService.java
Labels: feat

#70 feat: 가게 찜 기능 구현
  src/main/java/com/sparta/legendofdelivery/domain/dibs/controller/DibsController.java
  src/main/java/com/sparta/legendofdelivery/domain/dibs/dto/DibsResponseDto.java
  src/main/java/com/sparta/legendofdelivery/domain/dibs/entity/Dibs.java
  src/main/java/com/sparta/legendofdelivery/domain/dibs/repository/DibsRepository.java
  src/main/java/com/sparta/legendofdelivery/domain/dibs/service/DibsService.java
  src/main/java/com/sparta/legendofdelivery/domain/store/entity/Store.java
Labels: feat

#72 feat: 리뷰 수정 기능 추가
  src/main/java/com/sparta/legendofdelivery/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/legendofdelivery/domain/review/dto/UpdateReviewRequestDto.java
  src/main/java/com/sparta/legendofdelivery/domain/review/entity/ErrorCode.java
  src/main/java/com/sparta/legendofdelivery/domain/review/entity/Review.java
  src/main/java/com/sparta/legendofdelivery/domain/review/entity/successMessage.java
  src/main/java/com/sparta/legendofdelivery/domain/review/service/ReviewService.java
Labels: feat

#86 refactor: api url 변경 + dibscount 함수 분리
  src/main/java/com/sparta/legendofdelivery/domain/dibs/controller/DibsController.java
  src/main/java/com/sparta/legendofdelivery/domain/dibs/service/DibsService.java
  src/main/java/com/sparta/legendofdelivery/domain/like/controller/LikeController.java
  src/main/java/com/sparta/legendofdelivery/domain/store/entity/Store.java
  src/test/java/com/sparta/legendofdelivery/domain/dibs/controller/DibsControllerTest.java
  src/test/java/com/sparta/legendofdelivery/domain/dibs/service/DibsServiceTest.java
  src/test/java/com/sparta/legendofdelivery/domain/like/controller/LikeControllerTest.java
  src/test/java/com/sparta/legendofdelivery/domain/like/service/LikeServiceTest.java
Labels: update

#88 feat : README.md
  README.md
  img.png
  img_1.png
  src/main/java/com/sparta/legendofdelivery/domain/review/controller/ReviewController.java
Labels: feat

#90 test: Review 테스트 코드 작성!!
  src/main/java/com/sparta/legendofdelivery/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/legendofdelivery/domain/review/service/ReviewService.java
  src/test/java/com/sparta/legendofdelivery/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/sparta/legendofdelivery/domain/review/service/ReviewServiceTest.java
  src/test/java/com/sparta/legendofdelivery/domain/review/util/TestUtil.java
Labels: test

#94 update: 테스트 코드 작성
  src/main/java/com/sparta/legendofdelivery/domain/dibs/controller/DibsController.java
  src/test/java/com/sparta/legendofdelivery/domain/dibs/controller/DibsControllerTest.java
  src/test/java/com/sparta/legendofdelivery/domain/dibs/service/DibsServiceTest.java
  src/test/java/com/sparta/legendofdelivery/domain/like/controller/LikeControllerTest.java
  src/test/java/com/sparta/legendofdelivery/domain/like/service/LikeServiceTest.java
Labels: test
